pyrosocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("social.urls",namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name="social"


urlpatterns = [
    path('', views.profile, name='profile'),

    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    path('logout/', views.log_out, name="logout"),

    path('register/',views.register,name="register"),
    path('user/edit',views.edit_user,name="edit_account"),

    path('ticket/',views.ticket,name="ticket"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    path('posts/',views.post_list,name="post_list"),
    path('posts/post/<slug:tag_slug>/', views.post_list, name="post_list_by_tag"),
    path('posts/create_post/', views.create_post, name="create_post"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('like_post/',views.like_post,name="like_post"),
    path('save_post/',views.save_post,name="save_post"),
    path('users/',views.user_list,name="user_list"),
    path('users/<username>',views.user_detail,name="user_detail"),
    path('follow/',views.user_follow,name="user_follow"),
    path('users/<username>/<rel>',views.contact,name='user_contact'),
    path('posts/<pot_id>/comment',views.post_comment,name='post_comment'),
        


   
]

social/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, label="نام کاربری یا تلفن",
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, label="رمز عبور",
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    



class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone']



    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']
    

    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    


class UserEditForm(forms.ModelForm):



    class Meta:
        model=User
        fields=["first_name","last_name","phone","date_of_birth","job","bio","email","photo"]




    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    
    

    def clean_username(self):
        username=self.cleaned_data["username"] 
                                    #یوزر نیمی که کاربر وارد میکنه      یوزر نیمی که از  قبل هست
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("username already exists")
        return username
   



class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': "3"}), required=True, label='پیام')
    name = forms.CharField(max_length=250,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='نام')
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}),label='ایمیل')
    phone = forms.CharField(max_length=11,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='شماره تماس')
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label='موضوع')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['description', 'tags']




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'کامنت بزارید...',
                'class':'form-control input-sm'
            }),
        }

social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Post,Contact
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages


# Create your views here.




def log_out(request):
    logout(request)
    return HttpResponse("شما خارج شدید.")


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})




@login_required
def edit_user(request):
    if request.method=="POST":
        user_form =UserEditForm(request.POST,files=request.FILES,instance=request.user)
        if user_form.is_valid():
            user_form.save()

    else:
        user_form=UserEditForm(instance=request.user)

    return render (request,"registration/edit_user.html",{'user_form':user_form})




def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            #مبحث send_mail: به این صورت  است که ما تابع سند میل را مینویسیسم و سپس از سمت چپ به راست باید یک سری دیتا داخل یک پرانز ست 
            # که این دیتا ها عبارت است از اولی موضوع ایمیل دومی پیام یا مسیج ایمیل سومی ادرس ایمیل فرستنده و چهارمی ادرس ایمیل گیرنده
            send_mail(cd['subject'], message, 'matinkiaee.sy81@gmail.com', ['kiaeematin92@gmail.com'],
                      fail_silently=False)
            messages.success(request, 'پیام شما به پشتبانی')
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})




def post_list(request,tag_slug=None):
    posts=Post.objects.select_related("author").order_by("-total_likes")
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag=None
    if tag_slug:
      tag=get_object_or_404(Tag,slug=tag_slug)
      posts=Post.objects.filter(tags__in=[tag])

    page=request.GET.get('page')
    paginator=Paginator(posts,2)
    try:
        posts=paginator.page(page)

    except PageNotAnInteger:
        posts=paginator.page(1)

    except EmptyPage:
        posts=paginator.page(1)


    if request.headers.get('x-requested-with')=='XMLHttpRequest':
        return render (request,'social/list_ajax.html',{'posts':posts})
     
    context={
        "posts":posts,
        "tag":tag,
        "latest_users":latest_users,
    }

    return render(request, "social/list.html",context)



@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})



def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
    }
    return render(request, "social/detail.html", context)



@require_POST
@login_required
def like_post(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post=get_object_or_404("post",id=post_id)
        user=request.user


        if user in post.likes.all():
            post.likes.remove(user)
            liked=False

        else:
            post.likes.add(user)
            liked=True


        post_likes_count=post.likes.count()

        response_data={
            "liked":liked,
            "likes_count":post_likes_count
        }
    else:
        response_data={'error': 'Invalid post_id'}

    return JsonResponse(response_data)
         


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = Post.objects.get(id=post_id)
        user = request.user

        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True

        return JsonResponse({'saved': saved})
    return JsonResponse({'error': 'Invalid request'})



@login_required
def user_list(request):
    users=User.objects.filter(is_active=True)
    return render (request,"user/user_list.html",{'users':users})


@login_required
def user_detail(request, username):
    user=get_object_or_404(User,username=username,is_active=True)
    return render (request,"user/user_detail.html",{"user":user})





@login_required
@require_POST
def user_follow(request):
    user_id=request.POST.get("id")
    if user_id is not None:
        try:
            user=User.object.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow=False

            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow=True
            
            following_count=user.following.count()
            followers_count=user.followers.count()

            return JsonResponse({"follow":follow, "following_count":following_count, "followers_count":followers_count})
        

        except User.DoesNotExist:
            return JsonResponse ({"error":"user does not exist."})
        
    return JsonResponse ({'error':'invalid request.'})



def contact(request,rel,username):
    user=User.objects.get(username=username)
    if rel=="followings":
        users=user.get_followings()
    else:
        users=user.get_followers()

    return render(request,"user/user_list.html",{"users":users})




@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')

social/templates/partials/header.html
{% load static %}
<header class="tr-header">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
						data-target="#navbar-collapse">
						<span class="sr-only">تغییر وضعیت جهت یابی</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'social:post_list' %}"><i class="fab fa-instagram"></i>&nbsp;PyroSocial</a>
				</div><!-- /.navbar-header -->
				<div class="navbar-right">
					<div class="collapse navbar-collapse" id="navbar-collapse">
						<ul class="nav navbar-nav">
						</ul>
					</div>
				</div><!-- /.navbar-right -->
				<div class="navbar-left">
					<ul class="nav navbar-nav">
						<li>
							<div class="search-dashboard">
								<form>
									<input placeholder="جستجو کنید..." type="text">
									<button type="submit"><i class="fa fa-search"></i></button>
								</form>
							</div>
						</li>


{#						<li class="dropdown notification-list">#}
{#							<a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#"#}
{#								role="button" aria-haspopup="false" aria-expanded="false">#}
{#								<i class="fa fa-envelope noti-icon"></i>#}
{#								<span class="badge badge-success badge-pill noti-icon-badge">6</span>#}
{#							</a>#}
{#							<div class="dropdown-menu dropdown-menu-left dropdown-lg dropdown-new">#}
{#								<div class="dropdown-item noti-title">#}
{#									<h6 class="m-0">#}
{#										<span class="pull-left">#}
{#											<a href="#" class="text-dark"><small>نمایش همه</small></a>#}
{#										</span>گفتگو#}
{#									</h6>#}
{#								</div>#}
{##}
{#								<div class="slimScrollDiv"#}
{#									style="position: relative; overflow: hidden; width: auto; height: 416.983px;">#}
{#									<div class="slimscroll"#}
{#										style="max-height: 230px; overflow: hidden; width: auto; height: 416.983px;">#}
{#										<div id="Slim2">#}
{#											<a href="javascript:void(0);" class="dropdown-item notify-item nav-user">#}
{#												<div class="notify-icon"><img src="assets/img/users/1.jpg"#}
{#														class="img-responsive img-circle" alt=""> </div>#}
{#												<p class="notify-details">کریستیانو پیراید</p>#}
{#												<p class="text-muted font-13 mb-0 user-msg">سلام ، حال شما چطور است ؟#}
{#													جلسه بعدی ما چه زمانی است ؟</p>#}
{#											</a>#}
{#											<!--/ dropdown-item-->#}
{#											<a href="javascript:void(0);" class="dropdown-item notify-item nav-user">#}
{#												<div class="notify-icon"><img src="assets/img/users/2.jpg"#}
{#														class="img-responsive img-circle" alt=""> </div>#}
{#												<p class="notify-details">سام گارت</p>#}
{#												<p class="text-muted font-13 mb-0 user-msg">بله ، همه چیز مرتبه</p>#}
{#											</a>#}
{#											<!--/ dropdown-item-->#}
{#											<a href="javascript:void(0);" class="dropdown-item notify-item nav-user">#}
{#												<div class="notify-icon"><img src="assets/img/users/3.jpg"#}
{#														class="img-responsive img-circle" alt=""> </div>#}
{#												<p class="notify-details">کارن رابینسون</p>#}
{#												<p class="text-muted font-13 mb-0 user-msg">این خیلی عالیه ممنون</p>#}
{#											</a>#}
{#											<!--/ dropdown-item-->#}
{#											<a href="javascript:void(0);" class="dropdown-item notify-item nav-user">#}
{#												<div class="notify-icon"><img src="assets/img/users/4.jpg"#}
{#														class="img-responsive img-circle" alt=""> </div>#}
{#												<p class="notify-details">شری مارشال</p>#}
{#												<p class="text-muted font-13 mb-0 user-msg">سلام ، حال شما چطور است ؟#}
{#													جلسه بعدی ما چه زمانی است ؟</p>#}
{#											</a>#}
{#											<!--/ dropdown-item-->#}
{#											<a href="javascript:void(0);" class="dropdown-item notify-item nav-user">#}
{#												<div class="notify-icon"><img src="assets/img/users/5.jpg"#}
{#														class="img-responsive img-circle" alt=""> </div>#}
{#												<p class="notify-details">سارا میلارد</p>#}
{#												<p class="text-muted font-13 mb-0 user-msg">بله ، همه چیز مرتبه</p>#}
{#											</a>#}
{#											<!--/ dropdown-item-->#}
{#										</div>#}
{#										<!--/ .Slim-->#}
{#										<div class="slimScrollBar"#}
{#											style="background: rgb(158, 165, 171) none repeat scroll 0% 0%; width: 8px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px;">#}
{#										</div>#}
{#										<div class="slimScrollRail"#}
{#											style="width: 8px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.2; z-index: 90; right: 1px;">#}
{#										</div>#}
{#									</div>#}
{#									<!--/ slimscroll-->#}
{#								</div>#}
{#								<!--/ slimScrollDiv-->#}
{#								<a href="photo_chat.html" class="dropdown-item text-center notify-all">#}
{#									نمایش همه <i class="fa fa-arrow-left"></i>#}
{#								</a>#}
{#							</div>#}
{#							<!--/ dropdown-menu-->#}
{#						</li>#}

						<li class="dropdown mega-avatar">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            	{% if request.user.photo %}
								<span class="avatar w-32"><img src="{{ request.user.photo.url }}"
										class="img-resonsive img-circle" width="25" height="25" alt="..."></span>
                            	{% else %}
								<span class="avatar w-32"><img src="{% static 'images/profile/Avatar.png' %}"
										class="img-resonsive img-circle" width="25" height="25" alt="..."></span>
                            	{% endif %}
								<!-- hidden-xs hides the username on small devices so only the image appears. -->
{#								<span class="hidden-xs">#}
{#									{% if request.user.is_authenticated %}#}
{#                                        {{request.user.first_name|default:request.user.username }}#}
{#                                    {% else %}#}
{#                                        <a href="{% url 'social:login' %}" >ورود</a>#}
{#                                         <a href="{% url 'social:register' %}" >ثبت نام</a>#}
{#                                    {% endif %}#}
{#								</span>#}
							</a>
							<div class="dropdown-menu w dropdown-menu-scale pull-right">
								<a class="dropdown-item" href="{% url 'social:create_post' %}"><span>پست جدید</span></a>
{#								<a class="dropdown-item" href="#"><span>عضو شوید</span></a>#}
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'social:profile' %}"><span>پروفایل</span></a>
								<a class="dropdown-item" href="{% url 'social:edit_account' %}"><span>تنظیمات</span></a>
								<a class="dropdown-item" href="{% url 'social:ticket' %}">پشتیبانی</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'social:logout' %}">خروج</a>
							</div>
						</li><!-- /navbar-item -->

					</ul><!-- /.sign-in -->
				</div><!-- /.nav-left-->
			</div><!-- /.container -->
		</nav><!-- /.navbar -->
	</header><!-- Page Header -->

social/templates/partials/my-modal.html
{% load static %}
<!--/ profile -->
	<div id="myModal-{{ post_id }}" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-body">

					<div class="row">

						<div class="col-md-8 modal-image">
							<img class="img-responsive" src="{{my_post.images.first.image_file.url}}" alt="Image" />
								<br>
                                <div class="text-center">
                                           <p class="text-dark">
                                               {{ my_post.description }}
                                           </p>
                                        </div>
                                <br>
                                    <div class="text-center">
                                        {% for tag in my_post.tags.all %}
                                           <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
                                               <button> {{ tag.name }}</button>
                                           </a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                        </div>						</div>
                    <br>
						<!--/ col-md-8 -->
						<div class="col-md-4 modal-meta">
							<div class="modal-meta-top">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
									<span aria-hidden="true">×</span><span class="sr-only">بستن</span>
								</button>
								<!--/ button -->
								<div class="img-poster clearfix">
									<a href="#"><img class="img-responsive img-circle" src="{{ user.photo.url}}"
											alt="Image" /></a>
									<strong><a href="#">{{ user.get_full_name }}</a></strong>
{#									<span>12 دقیقه پیش</span><br />#}
{#									<a href="#" class="kafe kafe-btn-mint-small"><i class="fa fa-check-square"></i>#}
{#										دنبال کردن</a>#}
								</div>
								<!--/ img-poster -->

								<ul class="img-comment-list">
                                    {% for comment in my_post.comments.all %}
									<!--/ li -->
									<li>
										<div class="comment-img">
											<img src="{% static 'images/profile/avatar2.png' %}" class="img-responsive img-circle"
												alt="Image" />
										</div>
										<div class="comment-text">
											<strong><a href="#">{{ comment.name }}</a></strong>
											<p class="">{{ comment.body }}</p> <span class="date sub-text"> در {{ comment.created }} </span>
										</div>
									</li>
									<!--/ li -->
                                    {% endfor %}
								</ul>
								<!--/ comment-list -->

								<div class="modal-meta-bottom">
									<ul>
										<li><a class="modal-like" href="#"><i class="fa fa-heart"></i></a><span
												class="modal-one"> {{ my_post.total_likes }}</span> |
											<a class="modal-comment" href="#"><i class="fa fa-comments"></i></a><span>
												{{ my_post.comments.count}}</span>
										</li>
										<li>
											<span class="thumb-xs">
												<img class="img-responsive img-circle" src="{% static 'images/profile/avatar2.webp' %}"
													alt="Image">
											</span>
											<div class="comment-body">
                                                <form method="post" action="{% url 'social:post_comment' my_post.id %}" >
                                                    {% csrf_token %}
                                                    {{ form.as_div }}
                                                  <div class="col-12">
                                                    <button type="submit" class="btn btn-dark">ثبت</button>
                                                  </div>
                                                </form>
											</div>
											<!--/ comment-body -->
										</li>
									</ul>
								</div>
								<!--/ modal-meta-bottom -->

							</div>
							<!--/ modal-meta-top -->
						</div>
						<!--/ col-md-4 -->

					</div>
					<!--/ row -->
				</div>
				<!--/ modal-body -->

			</div>
			<!--/ modal-content -->
		</div>
		<!--/ modal-dialog -->
	</div>
	<!--/ modal -->

social/templates/partials/navigation.html
<!-- ==============================================
     Navigation Section
     =============================================== -->


	<!-- ==============================================
	 Navbar Second Section
	 =============================================== -->
     <section class="nav-sec">
		<div class="d-flex justify-content-between">
			<div class="p-2 nav-icon-lg dark-black">
				<a class="nav-icon" href="{% url 'social:post_list' %}"><em class="fa fa-home"></em>
					<span>خانه</span>
				</a>
			</div>
			<div class="p-2 nav-icon-lg clean-black">
				<a class="nav-icon" href="{% url 'social:post_list' %}"><em class="fa fa-list-ul"></em>
					<span>پیام</span>
				</a>
			</div>
			<div class="p-2 nav-icon-lg dark-black">
				<a class="nav-icon" href="{% url 'social:create_post' %}"><em class="fab fa-instagram"></em>
					<span>ایجاد پست</span>
				</a>
			</div>
			<div class="p-2 nav-icon-lg clean-black">
				<a class="nav-icon" href="{% url 'social:user_list' %}"><em class="fa fa-align-left"></em>
					<span>کابران</span>
				</a>
			</div>
			<div class="p-2 nav-icon-lg mint-green">
				<a class="nav-icon" href="{% url 'social:profile' %}"><em class="fa fa-user"></em>
					<span>پروفایل</span>
				</a>
			</div>
		</div>
	</section>