pyrosocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("social.urls",namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name="social"


urlpatterns = [
    path('', views.profile, name='profile'),

    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    path('logout/', views.log_out, name="logout"),

    path('register/',views.register,name="register"),
    path('user/edit',views.edit_user,name="edit_account"),

    path('ticket/',views.ticket,name="ticket"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    path('posts/',views.post_list,name="post_list"),
    path('posts/post/<slug:tag_slug>/', views.post_list, name="post_list_by_tag"),
    path('posts/create_post/', views.create_post, name="create_post"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('like_post/',views.like_post,name="like_post"),
    path('save_post/',views.save_post,name="save_post"),
    path('users/',views.user_list,name="user_list"),
    path('users/<username>',views.user_detail,name="user_detail"),
    path('follow/',views.user_follow,name="user_follow"),
    path('users/<username>/<rel>',views.contact,name='user_contact'),
    path('posts/<pot_id>/comment',views.post_comment,name='post_comment'),
        


   
]

social/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, label="نام کاربری یا تلفن",
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, label="رمز عبور",
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    



class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone']



    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']
    

    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    


class UserEditForm(forms.ModelForm):



    class Meta:
        model=User
        fields=["first_name","last_name","phone","date_of_birth","job","bio","email","photo"]




    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    
    

    def clean_username(self):
        username=self.cleaned_data["username"] 
                                    #یوزر نیمی که کاربر وارد میکنه      یوزر نیمی که از  قبل هست
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("username already exists")
        return username
   



class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': "3"}), required=True, label='پیام')
    name = forms.CharField(max_length=250,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='نام')
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}),label='ایمیل')
    phone = forms.CharField(max_length=11,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='شماره تماس')
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label='موضوع')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['description', 'tags']




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'کامنت بزارید...',
                'class':'form-control input-sm'
            }),
        }

social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Post,Contact
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages


# Create your views here.




def log_out(request):
    logout(request)
    return HttpResponse("شما خارج شدید.")


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})




@login_required
def edit_user(request):
    if request.method=="POST":
        user_form =UserEditForm(request.POST,files=request.FILES,instance=request.user)
        if user_form.is_valid():
            user_form.save()

    else:
        user_form=UserEditForm(instance=request.user)

    return render (request,"registration/edit_user.html",{'user_form':user_form})




def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            #مبحث send_mail: به این صورت  است که ما تابع سند میل را مینویسیسم و سپس از سمت چپ به راست باید یک سری دیتا داخل یک پرانز ست 
            # که این دیتا ها عبارت است از اولی موضوع ایمیل دومی پیام یا مسیج ایمیل سومی ادرس ایمیل فرستنده و چهارمی ادرس ایمیل گیرنده
            send_mail(cd['subject'], message, 'matinkiaee.sy81@gmail.com', ['kiaeematin92@gmail.com'],
                      fail_silently=False)
            messages.success(request, 'پیام شما به پشتبانی')
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})




def post_list(request,tag_slug=None):
    posts=Post.objects.select_related("author").order_by("-total_likes")
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag=None
    if tag_slug:
      tag=get_object_or_404(Tag,slug=tag_slug)
      posts=Post.objects.filter(tags__in=[tag])

    page=request.GET.get('page')
    paginator=Paginator(posts,2)
    try:
        posts=paginator.page(page)

    except PageNotAnInteger:
        posts=paginator.page(1)

    except EmptyPage:
        posts=paginator.page(1)


    if request.headers.get('x-requested-with')=='XMLHttpRequest':
        return render (request,'social/list_ajax.html',{'posts':posts})
     
    context={
        "posts":posts,
        "tag":tag,
        "latest_users":latest_users,
    }

    return render(request, "social/list.html",context)



@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})



def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
    }
    return render(request, "social/detail.html", context)



@require_POST
@login_required
def like_post(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post=get_object_or_404("post",id=post_id)
        user=request.user


        if user in post.likes.all():
            post.likes.remove(user)
            liked=False

        else:
            post.likes.add(user)
            liked=True


        post_likes_count=post.likes.count()

        response_data={
            "liked":liked,
            "likes_count":post_likes_count
        }
    else:
        response_data={'error': 'Invalid post_id'}

    return JsonResponse(response_data)
         


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = Post.objects.get(id=post_id)
        user = request.user

        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True

        return JsonResponse({'saved': saved})
    return JsonResponse({'error': 'Invalid request'})



@login_required
def user_list(request):
    users=User.objects.filter(is_active=True)
    return render (request,"user/user_list.html",{'users':users})


@login_required
def user_detail(request, username):
    user=get_object_or_404(User,username=username,is_active=True)
    return render (request,"user/user_detail.html",{"user":user})





@login_required
@require_POST
def user_follow(request):
    user_id=request.POST.get("id")
    if user_id is not None:
        try:
            user=User.object.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow=False

            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow=True
            
            following_count=user.following.count()
            followers_count=user.followers.count()

            return JsonResponse({"follow":follow, "following_count":following_count, "followers_count":followers_count})
        

        except User.DoesNotExist:
            return JsonResponse ({"error":"user does not exist."})
        
    return JsonResponse ({'error':'invalid request.'})



def contact(request,rel,username):
    user=User.objects.get(username=username)
    if rel=="followings":
        users=user.get_followings()
    else:
        users=user.get_followers()

    return render(request,"user/user_list.html",{"users":users})




@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')

social/templates/user/user_detail.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} profile {% endblock %}

{% block content %}



	<section class="profile">
		<div class="container-fluid">
			<div class="row">

				<div class="col-lg-3">
					<div class="profilebox hidden-xs hidden-sm" style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/4.jpg' %}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
					</div>
					<div class="profilebox hidden-xs hidden-sm" style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/1.jpg' %}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
					</div>
				</div>
				<div class="col-lg-6">
					<div class="profilebox-large hidden-xs hidden-sm" style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/9.jpg' %}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
					</div>
				</div>
				<div class="col-lg-3">
					<div class="profilebox hidden-xs hidden-sm" style="background: linear-gradient( rgba(34,34,34,0.45), rgba(34,34,34,0.45)), url('{% static 'img/posts/11.jpg' %}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
					</div>
					<div class="profilebox" style="background: linear-gradient( rgba(34,34,34,0.6), rgba(34,34,34,0.6)), url('{% static 'img/posts/12.jpg' %}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
					</div>
				</div>

			</div>
			<!--/ row-->
		</div>
		<!--/ container -->
	</section>
	<!--/ profile -->

	<!-- ==============================================
	 User Profile Section
	 =============================================== -->
	<section class="user-profile">
		<div class="container-fluid">
			<div class="row">

				<div class="col-lg-12">
					<div class="post-content">
						<div class="author-post text-center">
							
						</div><!-- /author -->
					</div><!-- /.post-content -->
				</div><!-- /col-sm-12 -->

			</div>
			<!--/ row-->
		</div>
		<!--/ container -->
	</section>
	<!--/ profile -->

	<!-- ==============================================
	 User Profile Section
	 =============================================== -->
	<section class="details">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">

					<div class="details-box row">
						<div class="col-lg-9">
							<div class="content-box">
								<h4>{{ user.get_full_name}} <i class="fa fa-check"></i></h4>
								<p>{{ user.bio |default:"این کاربر بایو ندارد."}}</p>
								<p>{{ user.job |default:"این کاربر شغلی ندارد."}}</p>
								<small><span>{{ user.username }}</span></small>

							</div>
							<!--/ media -->
						</div>
						<div class="col-lg-3">
                            {% if request.user == user %}
                                    {% if request.user in user.followers.all%}
                                        <button class="kafe-btn kafe-btn-default-mint" > آنفالو </button>ton>
                                    {% else %}
                                        <button class="kafe-btn kafe-btn-default-mint" > فالو </button>
                                    {% endif %}
                            {% else %}
                                    {% if request.user in user.followers.all%}
                                        <button class="kafe-btn kafe-btn-danger" id="follow-button"> آنفالو </button>
                                    {% else %}
                                        <button class="kafe-btn kafe-btn-mint" id="follow-button"> فالو </button>
                                    {% endif %}
                            {% endif %}
							<!--/ dropdown -->
						</div>
					</div>
					<!--/ details-box -->

				</div>
			</div>
		</div>
		<!--/ container -->
	</section>
	<!--/ profile -->

	<!-- ==============================================
	 Home Menu Section
	 =============================================== -->
	<section class="home-menu">
		<div class="container">
			<div class="row">

				<div class="menu-category">
                    {% with total_followers=user.followers.count total_following=user.following.count total_post=user.user_posts.count %}
					<ul class="menu">
						<li class="current-menu-item"><a href="photo_profile.html">پست&nbsp;<span>&nbsp;{{total_post}}&nbsp;</span></a></li>
						<li><a href="photo_followers.html">دنبال کننده&nbsp;<span class="followers-count">&nbsp;{{total_followers}}&nbsp;</span></a></li>
						<li><a href="photo_followers.html">نفر را دنبال می کند&nbsp;<span class="following-count">&nbsp;{{total_following}}&nbsp;</span></a></li>
					</ul>
                    {% endwith %}
				</div>

			</div>
			<!--/row -->
		</div>
		<!--/container -->
	</section>
	<!--/home-menu -->

	<!-- ==============================================
	 News Feed Section
	 =============================================== -->
	<section class="newsfeed">
		<div class="container">

			<div class="row">
				{% for post in user.user_posts.all %}
				<div class="col-lg-4">
					<a href="{% url 'social:post_detail' post.id %}" data-toggle="modal">
						<div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{post.images.first.image_file.url}}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
							<div class="explore-top">
								<div class="explore-like"><i class="fa fa-heart"></i> <span>{{ post.total_likes}}</span></div>
								<div class="explore-circle pull-left"></i> <span>{{ post.total_saves}}</span> <i class="far fa-bookmark"></i></div>
							</div>
						</div>
					</a>
				</div>
                {% endfor %}


			</div>
			<!--/ row -->


		</div>
		<!--/ container -->
	</section>
	<!--/ newsfeed -->

	<!-- ==============================================
	 Scripts
	 =============================================== -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
	<script>
	$('#Slim,#Slim2').slimScroll({
	        height:"auto",
			position: 'right',
			railVisible: true,
			alwaysVisible: true,
			size:"8px",
		});
	</script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function pruralize(data){
        if (data > 1 || data === 0) {
            return "s"
        } else {
            return ''
        }
    }
    $(document).ready(function() {
        $('#follow-button').click(function() {
            var button = $(this);

            $.ajax({
                type: 'POST',
                url: '{% url 'social:user_follow' %}',
                data: {'id': '{{user.id}}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.follow){
                        button.removeClass('kafe-btn-mint');
                        button.addClass('kafe-btn-danger');
                        button.text('آنفالو');
                    } else {
                        button.removeClass('kafe-btn-danger');
                        button.addClass('kafe-btn-mint');
                        button.text('فالو');
                    }
                    $('.followers-count').text(data.followers_count + 'Follower"+pruralize(data.followers_count)');
                    $('.following-count').text(data.following_count +'Following');
                },
            });
        });
    });
</script>

{% endblock %}

social/templates/user/user_list.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} users list {% endblock %}

{% block content %}

	 <section class="followers">
	  <div class="container-fluid">
	   <div class="row">

	    <div class="col-lg-8 col-lg-offset-2">

         <div class="followers-box full-width">
			<div class="followers-list">
                {% for user in users %}
					<div class="followers-body">
                    <a href="{% url 'social:user_detail' user.username %}">
                       
                    </a>
				 <div class="name-box">
				  <h4>{{ user.get_full_name}}</h4>
				  <span>{{ user.username }}</span>
				  <div class="followers-base">
                   <ul class="list-group">
                    <li class="list-group-item full-width">
					 <div class="pull-right" style="margin-left: 20px;">
                         {% for follower in user.followers.all|slice:"0:4" %}
                          <img src="{{ follower.photo.url}}" alt="" class="img-circle
                      </a> max-w-40 ">
                         {% endfor %}
                     <a href="{% url 'social:user_contact' user.username 'followers' %}">
					  <button class="btn btn-add-gray">
                              <i class="fa fa-plus"></i>
					  </button>
                     </a>
					  <span> {{ user.followers.count}} دنبال کننده </span>
					 </div><!--/ pull-left -->
					</li>
                    <li class="list-group-item full-width">
					 <div class="pull-right">
                         {% for following in user.following.all|slice:"0:4" %}
					  <img src="{{ following.photo.url }}" alt="" class="img-circle max-w-40 ">
						{% endfor %}
					  <a href="{% url 'social:user_contact' user.username 'following' %}">
					  <button class="btn btn-add-gray">
                              <i class="fa fa-plus"></i>
					  </button>
                     </a>
					  <span> {{ user.following.count}} نفر را دنبال می کند</span>
					 </div><!--/ pull-right -->
                    </li><!--/ list-group-item -->
                   </ul>
				  </div><!--/ followers-base -->
			     </div><!--/ name-box -->
				 <span><a href="#" class="kafe-btn kafe-btn-mint-small">دنبال کردن</a></span>
				</div><!--/ followers-body -->
                {% endfor %}

			</div><!--suggestions-list end-->
		</div>

		</div>

       </div><!--/ row-->
	  </div><!--/ container -->
	 </section><!--/ profile -->

     <!-- ==============================================
	 Scripts
	 =============================================== -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
	<script>
	$('#Slim,#Slim2').slimScroll({
	        height:"auto",
			position: 'right',
			railVisible: true,
			alwaysVisible: true,
			size:"8px",
		});
	</script>

{% endblock %}