pyrosocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("social.urls",namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name="social"


urlpatterns = [
    path('', views.profile, name='profile'),

    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    path('logout/', views.log_out, name="logout"),

    path('register/',views.register,name="register"),
    path('user/edit',views.edit_user,name="edit_account"),

    path('ticket/',views.ticket,name="ticket"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    path('posts/',views.post_list,name="post_list"),
    path('posts/post/<slug:tag_slug>/', views.post_list, name="post_list_by_tag"),
    path('posts/create_post/', views.create_post, name="create_post"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('like_post/',views.like_post,name="like_post"),
    path('save_post/',views.save_post,name="save_post"),
    path('users/',views.user_list,name="user_list"),
    path('users/<username>',views.user_detail,name="user_detail"),
    path('follow/',views.user_follow,name="user_follow"),
    path('users/<username>/<rel>',views.contact,name='user_contact'),
    path('posts/<pot_id>/comment',views.post_comment,name='post_comment'),
        


   
]

social/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, label="نام کاربری یا تلفن",
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, label="رمز عبور",
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    



class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone']



    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']
    

    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    


class UserEditForm(forms.ModelForm):



    class Meta:
        model=User
        fields=["first_name","last_name","phone","date_of_birth","job","bio","email","photo"]




    def clean_phone(self):
        phone=self.cleaned_data["phone"]
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists")
        return phone
    
    

    def clean_username(self):
        username=self.cleaned_data["username"] 
                                    #یوزر نیمی که کاربر وارد میکنه      یوزر نیمی که از  قبل هست
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("username already exists")
        return username
   



class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': "3"}), required=True, label='پیام')
    name = forms.CharField(max_length=250,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='نام')
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}),label='ایمیل')
    phone = forms.CharField(max_length=11,widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, label='شماره تماس')
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label='موضوع')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['description', 'tags']




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'کامنت بزارید...',
                'class':'form-control input-sm'
            }),
        }

social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Post,Contact
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages


# Create your views here.




def log_out(request):
    logout(request)
    return HttpResponse("شما خارج شدید.")


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})




@login_required
def edit_user(request):
    if request.method=="POST":
        user_form =UserEditForm(request.POST,files=request.FILES,instance=request.user)
        if user_form.is_valid():
            user_form.save()

    else:
        user_form=UserEditForm(instance=request.user)

    return render (request,"registration/edit_user.html",{'user_form':user_form})




def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            #مبحث send_mail: به این صورت  است که ما تابع سند میل را مینویسیسم و سپس از سمت چپ به راست باید یک سری دیتا داخل یک پرانز ست 
            # که این دیتا ها عبارت است از اولی موضوع ایمیل دومی پیام یا مسیج ایمیل سومی ادرس ایمیل فرستنده و چهارمی ادرس ایمیل گیرنده
            send_mail(cd['subject'], message, 'matinkiaee.sy81@gmail.com', ['kiaeematin92@gmail.com'],
                      fail_silently=False)
            messages.success(request, 'پیام شما به پشتبانی')
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})




def post_list(request,tag_slug=None):
    posts=Post.objects.select_related("author").order_by("-total_likes")
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag=None
    if tag_slug:
      tag=get_object_or_404(Tag,slug=tag_slug)
      posts=Post.objects.filter(tags__in=[tag])

    page=request.GET.get('page')
    paginator=Paginator(posts,2)
    try:
        posts=paginator.page(page)

    except PageNotAnInteger:
        posts=paginator.page(1)

    except EmptyPage:
        posts=paginator.page(1)


    if request.headers.get('x-requested-with')=='XMLHttpRequest':
        return render (request,'social/list_ajax.html',{'posts':posts})
     
    context={
        "posts":posts,
        "tag":tag,
        "latest_users":latest_users,
    }

    return render(request, "social/list.html",context)



@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})



def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
    }
    return render(request, "social/detail.html", context)



@require_POST
@login_required
def like_post(request):
    post_id=request.POST.get("post_id")
    if post_id is not None:
        post=get_object_or_404("post",id=post_id)
        user=request.user


        if user in post.likes.all():
            post.likes.remove(user)
            liked=False

        else:
            post.likes.add(user)
            liked=True


        post_likes_count=post.likes.count()

        response_data={
            "liked":liked,
            "likes_count":post_likes_count
        }
    else:
        response_data={'error': 'Invalid post_id'}

    return JsonResponse(response_data)
         


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = Post.objects.get(id=post_id)
        user = request.user

        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True

        return JsonResponse({'saved': saved})
    return JsonResponse({'error': 'Invalid request'})



@login_required
def user_list(request):
    users=User.objects.filter(is_active=True)
    return render (request,"user/user_list.html",{'users':users})


@login_required
def user_detail(request, username):
    user=get_object_or_404(User,username=username,is_active=True)
    return render (request,"user/user_detail.html",{"user":user})





@login_required
@require_POST
def user_follow(request):
    user_id=request.POST.get("id")
    if user_id is not None:
        try:
            user=User.object.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow=False

            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow=True
            
            following_count=user.following.count()
            followers_count=user.followers.count()

            return JsonResponse({"follow":follow, "following_count":following_count, "followers_count":followers_count})
        

        except User.DoesNotExist:
            return JsonResponse ({"error":"user does not exist."})
        
    return JsonResponse ({'error':'invalid request.'})



def contact(request,rel,username):
    user=User.objects.get(username=username)
    if rel=="followings":
        users=user.get_followings()
    else:
        users=user.get_followers()

    return render(request,"user/user_list.html",{"users":users})




@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')

social/templates/social/detail.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} post detail {% endblock %}

{% block content %}

	<section class="single-post">
		<div class="container">
			<div class="row">

				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-body">

							<div class="row">
								<div class="col-md-8 modal-image">
									<img class="img-responsive" src="{{post.images.first.image_file.url}}" alt="Image" />
                                <br>
                                <div class="text-center">
                                           <p class="text-dark">
                                               {{ post.description }}
                                           </p>
                                        </div>
                                <br>
                                    <div class="text-center">
                                        {% for tag in post.tags.all %}
                                           <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
                                               <button> {{ tag.name }}</button>
                                           </a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                        </div>

								</div>

								<!--/ col-md-8 -->
								<div class="col-md-4 modal-meta">
									<div class="modal-meta-top">
{#										<button type="button" class="close" data-dismiss="modal" aria-hidden="true">#}
{#											<span aria-hidden="true">×</span><span class="sr-only">بستن</span>#}
{#										</button>#}
										<!--/ button -->
										<div class="img-poster clearfix">
											<a href="#"><img class="img-responsive img-circle"
													
                                            <span>{{ post.created|date:"Y/m/d-H:i"}}</span><br />
											<strong><a href="#">{{ post.author.get_full_name }}</a></strong>
											<button id="save-post" class="kafe-btn kafe-btn-danger-small">
                                                 {% if user in post.saved_by.all %}
                                                    حذف از ذخیره
                                                {% else %}
                                                    ذخیره پست
                                                {% endif %}
                                            </button>
										</div>
										<!--/ img-poster -->

										<ul class="img-comment-list">
                                            {% for comment in post.comments.all %}
                                            <!--/ li -->
                                            <li>
                                                <div class="comment-img">
                                                    <img src="{% static 'images/profile/avatar2.png' %}" class="img-responsive img-circle"
                                                        alt="Image" />
                                                </div>
                                                <div class="comment-text">
                                                    <strong><a href="#">{{ comment.name }}</a></strong>
                                                    <p class="">{{ comment.body }}</p> <span class="date sub-text"> در {{ comment.created }} </span>
                                                </div>
                                            </li>
                                            <!--/ li -->
                                            {% endfor %}
										</ul>
										<!--/ comment-list -->

										<div class="modal-meta-bottom">
									<ul>

										<li>
                                            <a class="modal-like" href="#">
                                                {% if request.user in post.likes.all%}
                                                <i class="fa fa-heart" id="like-button"> UnLike </i>
                                                {% else %}
                                                <i class="fa fa-heartbeat" id="like-button"> like </i>
                                                {% endif %}
                                            </a>
                                            <span class="modal-one" id="likes-count"> {{ post.total_likes }}</span> |
											<a class="modal-comment" href="#"><i class="fa fa-comments"></i></a><span>
												{{ post.comments.count}}</span>
										</li>
										<li>
											<span class="thumb-xs">
												<img class="img-responsive img-circle" src="{% static 'images/profile/avatar2.webp' %}"
													alt="Image">
											</span>
											<div class="comment-body">
                                                <form method="post" action="{% url 'social:post_comment' post.id %}" >
                                                    {% csrf_token %}
                                                    {{ form.as_div }}
                                                  <div class="col-12">
                                                    <button type="submit" class="btn btn-dark">ثبت</button>
                                                  </div>
                                                </form>
											</div>
											<!--/ comment-body -->
										</li>
									</ul>
								</div>
										<!--/ modal-meta-bottom -->

									</div>

									<!--/ modal-meta-top -->
								</div>
								<!--/ col-md-4 -->

							</div>
							<!--/ row -->
						</div>
						<!--/ modal-body -->

					</div>
					<!--/ modal-content -->
				</div>
				<!--/ modal-dialog -->

			</div>
			<!--/ modal-dialog -->
		</div>
		<!--/ modal-dialog -->

	</section>
	<!--/ modal -->


    <div class="row top-row">


            <div class="text-center">
                <h3 class="text-dark">پست های مشابه</h3>
            </div>
    <br>
				{% for s_post in similar_post %}
				<div class="col-lg-3">
					<div class="tr-section">
						<div class="tr-post">
							<div class="entry-header">
								<div class="entry-thumbnail">
                                <a href="{% url 'social:post_detail' s_post.id %}">
									<img class="img-fluid" src="{{ s_post.images.first.image_file.url}}" alt="Image">
                                </a>
								</div><!-- /entry-thumbnail -->
							</div><!-- /entry-header -->
							<div class="post-content">
								<div class="author-post text-center">
										<a href="{% url 'social:user_detail' s_post.author.username %}">
                                            {% if user.photo %}
                                        		
                                             {% else %}
                                                <img class="img-fluid rounded-circle" src="{% static 'images/profile/Avatar.png' %}" alt="Image"></a>
                                            {% endif %}

								</div><!-- /author -->
								<div class="card-content">
									<h4>{{ s_post.author.get_full_name}}</h4>
									<span>{{s_post.author.username}}</span>
								</div>
								<a href="{% url 'social:post_detail' s_post.id %}" class="kafe-btn kafe-btn-mint-small full-width">مشاهده
								</a>
							</div><!-- /.post-content -->
						</div><!-- /.tr-post -->
					</div><!-- /.tr-post -->
				</div><!-- /col-sm-3 -->
                    {% empty %}
                    <div class="text-center">
                        هیچ پست مشابهی وجود ندارد
                    </div>

                {% endfor %}

			</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function() {
        $('#like-button').click(function() {
            var  button = $(this);

            $.ajax({
                type: 'POST',
                url: '{% url 'social:like_post' %}',
                data: {'post_id': {{post.id}}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.liked){
                        button.text('UnLike');
                        button.removeClass('fa-heartbeat');
                        button.addClass('fa-heart')
                    } else {
                        button.text('Like');
                        button.removeClass('fa-heart');
                        button.addClass('fa-heartbeat')
                    }
                    $('#likes-count').text(data.likes_count);
                },
            });
        });

        $("#save-post").click(function () {
            var button = $(this);
            $.ajax({
                type: "POST",
                url: "/save-post/",
                data: { 'csrfmiddlewaretoken': '{{ csrf_token }}', 'post_id': {{post.id}} },
                success: function (data) {
                    if (data.saved) {
                        button.text("حذف از ذخیره");
                    } else {
                        button.text("ذخیره پست");
                    }
                },
                error: function (error) {
                    console.log("خطا در ارسال درخواست Ajax: " + error);
                }
            });
        });

    });
</script>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
	<script>
	$('#Slim,#Slim2').slimScroll({
	        height:"auto",
			position: 'right',
			railVisible: true,
			alwaysVisible: true,
			size:"8px",
		});
	</script>

{% endblock %}

social/templates/social/list.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} posts list {% endblock %}

{% block content %}
    <div class="text-center">
        <h3 class="text-dark">شبکه اجتماعی برای اشتراک گذاری عکس</h3>
        {% if tag %}
        <h3>پست ها بر اساس تگ {{ tag.name }}</h3>
        {% endif %}
    </div>


	<!-- ==============================================
	 News Feed Section
	 =============================================== -->
	<section class="newsfeed">
		<div class="container">

			<div class="row one-row">
				<div class="col-lg-12">
					<a href="{% url 'social:user_list' %}">
						<h4>نمایش همه</h4>
					</a>
				</div>
			</div>

			<div class="row top-row">
				{% for user in latest_users %}
				<div class="col-lg-3">
					<div class="tr-section">
						<div class="tr-post">
							<div class="entry-header">
								<div class="entry-thumbnail">
                                <a href="{% url 'social:user_detail' user.username %}">
                                    {% if user.photo %}
									<img class="img-fluid" src="{{ user.photo.url}}" alt="Image">
                                    {% else %}
                                       <img class="img-fluid" src="{% static 'images/profile/Avatar.png' %}" alt="Image">
                                    {% endif %}
                                </a>
								</div><!-- /entry-thumbnail -->
							</div><!-- /entry-header -->
							<div class="post-content">
								<div class="author-post text-center">
										<a href="{% url 'social:user_detail' user.username %}">
                                            {% if user.photo %}
                                        		<img class="img-fluid rounded-circle" src="{{ user.photo.url}}" alt="Image"></a>
                                             {% else %}
                                                <img class="img-fluid rounded-circle" src="{% static 'images/profile/Avatar.png' %}" alt="Image"></a>
                                            {% endif %}

								</div><!-- /author -->
								<div class="card-content">
									<h4>{{ user.get_full_name}}</h4>
									<span>{{user.username}}</span>
								</div>
								<a href="{% url 'social:user_detail' user.username %}" class="kafe-btn kafe-btn-mint-small full-width">مشاهده
								</a>
							</div><!-- /.post-content -->
						</div><!-- /.tr-post -->
					</div><!-- /.tr-post -->
				</div><!-- /col-sm-3 -->
                {% endfor %}

			</div>

			<div class="row one-row">
				<div class="col-lg-12">
					<h4>بخش کاوش و جستجو</h4>
				</div>
			</div>

			<div id ="post-list">
            	<div class="row">
					{% for post in posts %}
				<div class="col-lg-4 m-4">
					<a href="{{ post.get_absolute_url }}" data-toggle="modal">
						<div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{post.images.first.image_file.url}}') no-repeat;
		          background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
							<div class="explore-top">
								<div class="explore-like"><i class="fa fa-heart"></i> <span>{{ post.total_likes}}</span></div>
								<div class="explore-circle pull-left"><span>{{ post.total_saves}}&nbsp;</span><i class="far fa-bookmark"></i></div>
							</div>
							<div class="explore-body">
								<div class="">
                                    
                                </div>
							</div>

						</div>
					</a>
                <h6 class="">{{ post.created|date:"Y/m/d-H:i"}}</h6>
                {% for tag in post.tags.all %}
                   <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
                       <button> {{ tag.name }}</button>
                   </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
				</div>

				<!--/ col-lg-4 -->
					{% endfor %}
                </div>
			</div>
		<br>
		<button id="load-more" class="center-block text-info">بار‌گذاری بیشتر</button>
		</div>
		<!--/ container -->
	</section>
	<!--/ newsfeed -->


	<!-- ==============================================
	 Scripts
	 =============================================== -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
	<script>
	$('#Slim,#Slim2').slimScroll({
	        height:"auto",
			position: 'right',
			railVisible: true,
			alwaysVisible: true,
			size:"8px",
		});
	</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function(){
        var page = 2;
        $('#load-more').click(function(){
            $.ajax({
                type : 'GET',
                url : "{% if tag %}{% url 'social:post_list_by_tag' tag.slug %}{% else %}{% url 'social:post_list' %}{% endif %}" + "?page=" + page,
                dataType : 'html',
                success : function(data){
                    $('#post-list').append(data);
                    page += 1;
                }
            });
        });
    });
</script>

{% endblock %}

social/templates/social/list_ajax.html
<div class="row">
    {% if posts %}
    <br>
    <br>
    {% endif %}
            {% for post in posts %}
        <div class="col-lg-4 m-4">
            <a href="{{ post.get_absolute_url }}" data-toggle="modal">
                <div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{post.images.first.image_file.url}}') no-repeat;
          background-size: cover;
          background-position: center center;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;">
                    <div class="explore-top">
                        <div class="explore-like"><i class="fa fa-heart"></i> <span>{{ post.total_likes}}</span></div>
                        <div class="explore-circle pull-left"><span>{{ post.total_saves}}&nbsp;</span><i class="far fa-bookmark"></i></div>
                    </div>
                    <div class="explore-body">
                        <div class="">
                            <img class="img-circle" src="{{ post.author.photo.url}}" alt="user">
                        </div>
                    </div>
    
                </div>
            </a>
        <h6 class="">{{ post.created|date:"Y/m/d-H:i"}}</h6>
        {% for tag in post.tags.all %}
           <a class="text-dark" href="{% url 'social:post_list_by_tag' tag.slug %}">
               <button> {{ tag.name }}</button>
           </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
        </div>
    
        <!--/ col-lg-4 -->
            {% endfor %}
    </div>